### ISSUE TITLE
Techguns Crashing my game every 10 minutes or less

### ISSUE THREAD

**Issue by noahthomas2014** [pWn3d1337/Techguns2#124] opened 2019-04-22 15:01 UTC
Every time I load or make a world my game always crashes and I have no idea why but I'll post the crash report here.
[crash-2019-04-22_15.51.46-server.txt](https://github.com/pWn3d1337/Techguns2/files/3103773/crash-2019-04-22_15.51.46-server.txt)
that should be it.

**Comment by pWn3d1337** [comment] 2019-04-22 16:35
The log does not directly reference techguns. Could be anything.

**Comment by pWn3d1337** [comment] 2019-04-28 08:50
According to someone in the discord the crash could be caused by using forge builds 2835-2836

**Comment by LemADEC** [comment] 2019-07-01 07:18
Already fixed in Forge, this issue can be closed

**Closed** 2019-10-19 11:04 UTC
Labels: Unconfirmed
